### PR TITLE
Add the detect-key flag functionality

### PR DESCRIPTION
**Pull request by johannesCmayer**
`python keebie.py --detect-key` now waits for one keypress and prints the key returned. 

I made some minor changes to logging, such that keebie only prints the key name and nothing else, such that the output becomes more usable. 

I added the `--quiet` flag that makes it so that grabbing, ungrabbing, closing of devices, and one newline is not printed. This functionality is also used if `--detect-key` is given.

### CODE REVIEW

**Comment by Michael-E-B** [comment]
I'm a little uncertain why `--detect-key` is needed - and there are a few things I think should be changed with commenting for consistency - but this looks like it should do what it sets out to well enough.

**Comment by daisyUniverse** [comment]
I can see it being potentially useful for quick reference and sanity checking, and the code looks good to me
I'm open to merging it if @Michael-E-B doesn't see any issues, and he doesn't seem to, so I'll go ahead with it

**Comment by Michael-E-B** [comment]
Go for it, I'll probably push some small stuff to it later today.

**Comment by Michael-E-B** [comment]
Noticing that `-k` seems to report keys as held when they shouldn't be. More investigation needed, I'll look into it.

Edit: Added test code to diagnose and now I can't reproduce it. Still working on it.

**Comment by Michael-E-B** [comment]
Bug is gone and I cant get it back (just like my hopes and dreams!), go figure.

**Comment by johannesCmayer** [comment]
The reason I added this feature is that I want to have a helper script, that can ask me for every command listed in a file, in sequence, what keybinding that command should be set to. Then do some more postprocessing on that (such as having similar commands on the same key when a modifier is held down). And then dump that as a config file for keebie. 

This is useful because I have labeled the keys on my shortcut keyboard with what they do. So it is much more convenient to have something that basically asks "Where is the button on the keyboard".

Seemed easier to get the functionality this way, than to write it from scratch. And it could probably be useful in other ways, e.g. testing, as mentioned.

**Pull request merged**
